version: "3.7"
services:
  movies_app:
    container_name: movies
    image: node:13
    user: "node"
    working_dir: /home/react
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/react
    command: bash -c "npm install && npm start"
    ports:
      #HOST:CONTAINER - HOST = maquina local
      - "3001:3000"